name: Production Deployment

on:
  push:
    branches:
      - backend-new

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: build container
        run: docker build -t opencrab:latest .

      - name: kill existing container if exists
        run: docker rm -f opencrab || true
      
      - name: run container
        run: docker run -d --name opencrab -p 8000:8000 -e HTTPS_PROXY=http://192.168.10.1:7890 -e AGENT_ENV_VAULT_MASTER_KEY=tmpkey -v /home/xciphand/agent_data:/app opencrab:latest